version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Skipping yum update..."

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."

  build:
    commands:
      - echo "Build started"
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed"
      - aws ssm get-parameter --name maddy-test --with-decryption --query "Parameter.Value" --output text > private_key.pem
      - chmod 600 private_key.pem
      # Copy the built WAR file to S3 bucket
      - aws s3 cp /codebuild/output/src*/src/webapp/target/webapp.war s3://tf-test-backend-bucket/path/to/store/webapp.war --sse AES256 --region ap-south-1
