version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Skip yum update as it may not be available in some CodeBuild environments
      - echo "Skipping yum update..."

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."

  build:
    commands:
      - echo "Build started"
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed"
      - aws ssm get-parameter --name arn:aws:ssm:us-east-1:787367675716:parameter/maddy-test --with-decryption --query "Parameter.Value" --output text > private_key.pem
      - scp -i private_key.pem target/webapp.war ec2-user@13.126.207.243:/home/ec2-user/webapp.war
