version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Skipping yum update..."

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."

  build:
    commands:
      - echo "Build started"
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed"
      - aws ssm get-parameter --name maddy-test --with-decryption --query "Parameter.Value" --output text > private_key.pem
      - chmod 600 private_key.pem
      - ls -la /codebuild/output/ # Print the content of the output directory for debugging
      - cd /codebuild/output/
      - scp -o StrictHostKeyChecking=no -i private_key.pem $(find . -name webapp.war -type f) ubuntu@44.204.28.186:/home/ubuntu/webapp.war
