version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Skipping yum update..."

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."

  build:
    commands:
      - echo "Build started"
      - pwd  # Print the current working directory
      - ls -la  # List the contents of the project directory
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed"
      - aws ssm get-parameter --name maddy-test --with-decryption --query "Parameter.Value" --output text > private_key.pem
      - ls -la target  # List the contents of the target directory
      - scp -v -i private_key.pem target/webapp.war ubuntu@44.204.28.186:/home/ubuntu/webapp.war
